# Generated by Django 3.2 on 2021-04-18 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scan_file', models.FileField(upload_to='passport')),
                ('document_number', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('birth_date', models.DateField()),
                ('personal_number', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('issue_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('issuing_authority', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinformation')),
            ],
            options={
                'verbose_name': 'Passport',
                'verbose_name_plural': 'Passports',
            },
        ),
    ]
